import { describe, expect, it } from 'vitest';
import ExcelJS from 'exceljs';
import { createSupplierImportService, previewSupplierImport, supplierImportTemplate } from '../../../src/modules/parties/supplier-import.js';
const organizationId = '00000000-0000-4000-8000-000000000001';
async function workbook(rows: string[][], headers = ['Name', 'Phone', 'Email', 'Address', 'Notes']) { const book = new ExcelJS.Workbook(); const sheet = book.addWorksheet('Suppliers'); sheet.addRow(headers); rows.forEach((row) => sheet.addRow(row)); return Buffer.from(await book.xlsx.writeBuffer()); }
describe('supplier Excel import', () => {
  it('creates its template and previews valid rows', async () => { const book = new ExcelJS.Workbook(); await book.xlsx.load(await supplierImportTemplate() as any); expect(book.getWorksheet('Suppliers')!.getCell('A1').value).toBe('Name'); await expect(previewSupplierImport(await workbook([['Textiles Co', '01012345678', '', '', '']] ))).resolves.toMatchObject({ valid: true, rows: [{ name: 'Textiles Co', phone: '01012345678' }] }); });
  it('rejects malformed workbooks, headers, empty files, invalid and duplicate rows', async () => { await expect(previewSupplierImport(Buffer.from('bad'))).resolves.toMatchObject({ errors: [{ message: 'INVALID_WORKBOOK' }] }); await expect(previewSupplierImport(await workbook([], ['Name']))).resolves.toMatchObject({ errors: [{ message: 'EXPECTED_SUPPLIER_COLUMNS' }] }); await expect(previewSupplierImport(await workbook([]))).resolves.toMatchObject({ errors: [{ message: 'NO_ROWS' }] }); await expect(previewSupplierImport(await workbook([['x', '', '', '', ''], ['Textiles Co', '', '', '', ''], ['textiles co', '', '', '', '']]))).resolves.toMatchObject({ errors: [{ row: 2, message: 'INVALID_SUPPLIER' }, { row: 4, message: 'DUPLICATE_IN_FILE' }] }); });
  it('imports only non-conflicting complete workbooks atomically', async () => { const created: string[] = []; const service = createSupplierImportService({ findNames: async () => [], createAtomically: async (_organizationId, _actor, suppliers) => { created.push(...suppliers.map((supplier) => supplier.name)); } }); const valid = await workbook([['Textiles Co', '', '', '', ''], ['Shoes Co', '', '', '', ''], ['', '', '', '', '']]); await expect(service.import(organizationId, 'actor', valid)).resolves.toMatchObject({ ok: true, imported: 2 }); expect(created).toEqual(['Textiles Co', 'Shoes Co']); const conflict = createSupplierImportService({ findNames: async () => ['Textiles Co'], createAtomically: async () => { throw Error('must not write'); } }); const result = await conflict.import(organizationId, 'actor', valid); expect(result.ok).toBe(false); if (!result.ok) expect(result.preview.errors).toEqual([{ row: 2, message: 'SUPPLIER_EXISTS' }]); await expect(service.import(organizationId, 'actor', await workbook([]))).resolves.toMatchObject({ ok: false }); });
});
