import { randomUUID } from 'node:crypto';
import ExcelJS from 'exceljs';
import { createSupplierSchema } from '@ahmed-store/contracts';

export type SupplierImportRow = { row: number; name: string; phone: string | null; email: string | null; address: string | null; notes: string | null };
export type SupplierImportPreview = { valid: boolean; rows: SupplierImportRow[]; errors: Array<{ row: number; message: string }> };
export interface SupplierImportRepository { findNames(organizationId: string, names: string[]): Promise<string[]>; createAtomically(organizationId: string, actorUserId: string, suppliers: Array<{ id: string; name: string; phone: string | null; email: string | null; address: string | null; notes: string | null }>): Promise<void>; }
export async function supplierImportTemplate() { const book = new ExcelJS.Workbook(); const sheet = book.addWorksheet('Suppliers', { views: [{ state: 'frozen', ySplit: 1 }] }); sheet.columns = [{ header: 'Name', width: 30 }, { header: 'Phone', width: 20 }, { header: 'Email', width: 32 }, { header: 'Address', width: 40 }, { header: 'Notes', width: 40 }]; sheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } }; sheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF163A70' } }; return Buffer.from(await book.xlsx.writeBuffer()); }
export async function previewSupplierImport(file: Buffer): Promise<SupplierImportPreview> { try { const book = new ExcelJS.Workbook(); await book.xlsx.load(file as any); const sheet = book.getWorksheet('Suppliers'); const headers = ['Name', 'Phone', 'Email', 'Address', 'Notes']; if (!sheet || headers.some((header, index) => sheet.getRow(1).getCell(index + 1).text.trim() !== header)) return { valid: false, rows: [], errors: [{ row: 1, message: 'EXPECTED_SUPPLIER_COLUMNS' }] }; const rows: SupplierImportRow[] = []; const errors: Array<{ row: number; message: string }> = []; const names = new Set<string>(); for (let row = 2; row <= sheet.rowCount; row += 1) { const values = [1, 2, 3, 4, 5].map((column) => sheet.getRow(row).getCell(column).text.trim()); if (!values.some(Boolean)) continue; const [name, phoneText, emailText, addressText, notesText] = values; const phone = phoneText || null; const email = emailText || null; const address = addressText || null; const notes = notesText || null; const parsed = createSupplierSchema.safeParse({ name, phone, email, address, notes }); if (!parsed.success) { errors.push({ row, message: 'INVALID_SUPPLIER' }); continue; } if (names.has(parsed.data.name.toLocaleLowerCase())) { errors.push({ row, message: 'DUPLICATE_IN_FILE' }); continue; } names.add(parsed.data.name.toLocaleLowerCase()); rows.push({ row, ...parsed.data }); } if (!rows.length && !errors.length) errors.push({ row: 2, message: 'NO_ROWS' }); return { valid: errors.length === 0, rows, errors }; } catch { return { valid: false, rows: [], errors: [{ row: 1, message: 'INVALID_WORKBOOK' }] }; } }
export function createSupplierImportService(repository: SupplierImportRepository) { return { template: supplierImportTemplate, preview: previewSupplierImport, async import(organizationId: string, actorUserId: string, file: Buffer) { const preview = await previewSupplierImport(file); if (!preview.valid) return { ok: false as const, preview }; const names = new Set((await repository.findNames(organizationId, preview.rows.map((row) => row.name))).map((name) => name.toLocaleLowerCase())); const errors = preview.rows.filter((row) => names.has(row.name.toLocaleLowerCase())).map((row) => ({ row: row.row, message: 'SUPPLIER_EXISTS' })); if (errors.length) return { ok: false as const, preview: { ...preview, valid: false, errors } }; await repository.createAtomically(organizationId, actorUserId, preview.rows.map(({ row: _row, ...supplier }) => ({ id: randomUUID(), ...supplier }))); return { ok: true as const, imported: preview.rows.length }; } }; }
