import { describe, expect, it } from 'vitest';
import ExcelJS from 'exceljs';
import { createSalesExportService, salesExportCsv, salesExportXlsx, type SalesExportRepository } from '../../../src/modules/reporting/sales-export.js';

const organizationId='38e7c8c5-ec67-4fa4-b4b8-7d2156be5d55', actorUserId='63c8a4d3-1a33-4d0a-bb8f-7d2156be5d55';
const line={saleId:'sale-1',occurredAt:new Date('2026-01-01T00:00:00.000Z'),customerName:'Ahmed, "Ali"',warehouseName:'Main',productName:'Shirt',sku:'SH-1',quantity:'2.0000',unitPrice:'10.0000',discount:'1.0000',lineTotal:'19.0000',invoiceTotal:'19.0000',status:'POSTED' as const};
describe('sales export',()=>{it('creates a UTF-8 one-row-per-sale-line CSV with escaped columns',()=>{expect(salesExportCsv([line])).toBe('\uFEFFinvoice_id,occurred_at,customer,warehouse,product,sku,quantity,unit_price,discount,line_total,invoice_total,status\r\n"sale-1","2026-01-01T00:00:00.000Z","Ahmed, ""Ali""","Main","Shirt","SH-1","2.0000","10.0000","1.0000","19.0000","19.0000","POSTED"\r\n');expect(salesExportCsv([])).toContain('invoice_id');});it('lists scoped lines then writes an audit record',async()=>{const calls:string[]=[];const repository:SalesExportRepository={list:async(id,query)=>{calls.push(`${id}:${query.warehouseId}`);return[line];},audit:async(id,user)=>{calls.push(`${id}:${user}`);}};const csv=await createSalesExportService(repository).exportCsv(organizationId,actorUserId,{warehouseId:'a0ac2c74-c66c-4a28-b658-34c88db36e8a'});expect(csv).toContain('sale-1');expect(calls).toEqual([`${organizationId}:a0ac2c74-c66c-4a28-b658-34c88db36e8a`,`${organizationId}:${actorUserId}`]);});});

describe('sales Excel export',()=>{it('creates a typed, formatted workbook with one row per sales line',async()=>{const output=await salesExportXlsx([line]);const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(output as any);const sheet=workbook.getWorksheet('Sales history')!;expect(sheet.getRow(1).getCell(1).value).toBe('Invoice ID');expect(sheet.getRow(2).values).toMatchObject([, 'sale-1', line.occurredAt, 'Ahmed, "Ali"', 'Main', 'Shirt', 'SH-1', 2, 10, 1, 19, 19, 'POSTED']);expect(sheet.getColumn('G').numFmt).toBe('#,##0.0000');expect(sheet.views[0]).toMatchObject({ state:'frozen', ySplit:1 });expect(sheet.getRow(1).font?.bold).toBe(true);});it('uses the same scoped rows and audit trail for Excel exports',async()=>{const calls:string[]=[];const repository:SalesExportRepository={list:async()=>{calls.push('list');return[];},audit:async()=>{calls.push('audit');}};const output=await createSalesExportService(repository).exportXlsx(organizationId,actorUserId,{});const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(output as any);expect(workbook.getWorksheet('Sales history')!.rowCount).toBe(1);expect(calls).toEqual(['list','audit']);});});
