import { describe, expect, it } from 'vitest';
import ExcelJS from 'exceljs';
import { categoryImportTemplate, createCategoryImportService, previewCategoryImport, type CategoryImportRepository } from '../../../src/modules/catalogue/category-import.js';

async function workbook(rows: string[], header = 'Name') { const book = new ExcelJS.Workbook(); const sheet = book.addWorksheet('Categories'); sheet.getCell('A1').value = header; rows.forEach((name, index) => { sheet.getCell(index + 2, 1).value = name; }); return Buffer.from(await book.xlsx.writeBuffer()); }
const organizationId = '38e7c8c5-ec67-4fa4-b4b8-7d2156be5d55';
describe('category Excel import', () => {
  it('generates a readable template and validates valid category rows', async () => { const template = await categoryImportTemplate(); const book = new ExcelJS.Workbook(); await book.xlsx.load(template as any); expect(book.getWorksheet('Categories')!.getCell('A1').value).toBe('Name'); await expect(previewCategoryImport(await workbook(['Shirts', 'Trousers']))).resolves.toEqual({ valid: true, rows: [{ row: 2, name: 'Shirts' }, { row: 3, name: 'Trousers' }], errors: [] }); });
  it('rejects missing headers, invalid rows, duplicates, empty files, and invalid workbooks', async () => { await expect(previewCategoryImport(await workbook(['Shirts'], 'Category'))).resolves.toMatchObject({ valid: false, errors: [{ row: 1, message: 'EXPECTED_NAME_COLUMN' }] }); const wrongSheet = new ExcelJS.Workbook(); wrongSheet.addWorksheet('Other'); await expect(previewCategoryImport(Buffer.from(await wrongSheet.xlsx.writeBuffer()))).resolves.toMatchObject({ valid: false, errors: [{ row: 1, message: 'EXPECTED_NAME_COLUMN' }] }); await expect(previewCategoryImport(await workbook(['x', 'Shirts', 'shirts']))).resolves.toMatchObject({ valid: false, errors: [{ row: 2, message: 'INVALID_NAME' }, { row: 4, message: 'DUPLICATE_IN_FILE' }] }); await expect(previewCategoryImport(await workbook(['', 'Shirts']))).resolves.toMatchObject({ valid: true, rows: [{ row: 3, name: 'Shirts' }] }); await expect(previewCategoryImport(await workbook([]))).resolves.toMatchObject({ valid: false, errors: [{ row: 2, message: 'NO_ROWS' }] }); await expect(previewCategoryImport(Buffer.from('not-a-workbook'))).resolves.toMatchObject({ valid: false, errors: [{ row: 1, message: 'INVALID_WORKBOOK' }] }); });
  it('imports only a fully valid, non-conflicting workbook and audits atomically', async () => { const calls: string[] = []; const repository: CategoryImportRepository = { findNames: async (_organizationId, names) => { calls.push(names.join(',')); return []; }, createAtomically: async (_organizationId, _actorUserId, categories) => { calls.push(categories.map((category) => category.name).join(',')); } }; const service = createCategoryImportService(repository); await expect(service.import(organizationId, 'actor', await workbook(['Shirts']))).resolves.toMatchObject({ ok: true, imported: 1 }); await expect(service.import(organizationId, 'actor', await workbook(['Shirts', 'Shoes']))).resolves.toMatchObject({ ok: true, imported: 2 }); expect(calls).toEqual(['Shirts', 'Shirts', 'Shirts,Shoes', 'Shirts,Shoes']); });
  it('does not create any categories if database names conflict or validation fails', async () => { let created = false; const service = createCategoryImportService({ findNames: async () => ['Shirts'], createAtomically: async () => { created = true; } }); await expect(service.import(organizationId, 'actor', await workbook(['Shirts']))).resolves.toMatchObject({ ok: false, preview: { errors: [{ row: 2, message: 'CATEGORY_EXISTS' }] } }); await expect(service.import(organizationId, 'actor', await workbook([]))).resolves.toMatchObject({ ok: false }); expect(created).toBe(false); });
});
