import { describe, expect, it } from 'vitest';
import ExcelJS from 'exceljs';
import { createProductImportService, previewProductImport, productImportTemplate } from '../../../src/modules/catalogue/product-import.js';

const organizationId = '00000000-0000-4000-8000-000000000001';
async function workbook(rows: string[][], headers = ['Name', 'SKU', 'Barcode', 'Category', 'Sale Price', 'Cost Price']) { const book = new ExcelJS.Workbook(); const sheet = book.addWorksheet('Products'); sheet.addRow(headers); rows.forEach((row) => sheet.addRow(row)); return Buffer.from(await book.xlsx.writeBuffer()); }
describe('product Excel import', () => {
  it('creates a readable template and previews valid products', async () => { const template = await productImportTemplate(); const book = new ExcelJS.Workbook(); await book.xlsx.load(template as any); expect(book.getWorksheet('Products')!.getRow(1).getCell(2).value).toBe('SKU'); await expect(previewProductImport(await workbook([['Shirt', 'sh-1', '123', 'Clothes', '20.0000', '10.0000']]))).resolves.toEqual({ valid: true, rows: [{ row: 2, name: 'Shirt', sku: 'SH-1', barcode: '123', category: 'Clothes', salePrice: '20.0000', costPrice: '10.0000' }], errors: [] }); });
  it('rejects malformed headers, rows, duplicates, empty workbooks, and invalid files', async () => { await expect(previewProductImport(await workbook([['Shirt', 'SH-1', '', '', '20', '10']], ['Name']))).resolves.toMatchObject({ valid: false, errors: [{ message: 'EXPECTED_PRODUCT_COLUMNS' }] }); await expect(previewProductImport(await workbook([['x', 'SH-1', '', '', '20', '10'], ['Shirt', 'SH-1', '', '', '20', '10'], ['Shoe', 'SH-1', '', '', '20', '10'], ['Hat', 'HA-1', '123', '', '20', '10'], ['Cap', 'CA-1', '123', '', '20', '10']]))).resolves.toMatchObject({ valid: false, errors: [{ row: 2, message: 'INVALID_PRODUCT' }, { row: 4, message: 'DUPLICATE_SKU_IN_FILE' }, { row: 6, message: 'DUPLICATE_BARCODE_IN_FILE' }] }); await expect(previewProductImport(await workbook([]))).resolves.toMatchObject({ valid: false, errors: [{ message: 'NO_ROWS' }] }); await expect(previewProductImport(Buffer.from('bad'))).resolves.toMatchObject({ valid: false, errors: [{ message: 'INVALID_WORKBOOK' }] }); });
  it('imports all valid products atomically and rejects category or duplicate conflicts', async () => { const created: string[] = []; const service = createProductImportService({ findCategories: async () => [{ id: 'category-1', name: 'Clothes' }], findExisting: async () => ({ skus: [], barcodes: [] }), createAtomically: async (_org, _actor, products) => { created.push(...products.map((product) => product.sku)); } }); const valid = await workbook([['Shirt', 'SH-1', '123', 'Clothes', '20', '10'], ['', '', '', '', '', ''], ['Hat', 'HA-1', '', '', '15', '7']]); await expect(service.import(organizationId, 'actor', valid)).resolves.toMatchObject({ ok: true, imported: 2 }); expect(created).toEqual(['SH-1', 'HA-1']); const missing = createProductImportService({ findCategories: async () => [], findExisting: async () => ({ skus: ['SH-1'], barcodes: ['123'] }), createAtomically: async () => { throw Error('must not write'); } }); const result = await missing.import(organizationId, 'actor', valid); expect(result.ok).toBe(false); if (!result.ok) expect(result.preview.errors.map((error) => error.message)).toEqual(['CATEGORY_UNAVAILABLE', 'SKU_EXISTS', 'BARCODE_EXISTS']); await expect(service.import(organizationId, 'actor', await workbook([]))).resolves.toMatchObject({ ok: false }); });
});
